platform :ios, '15.0'
use_frameworks!

target 'DroneWatchDJIBootstrap' do
  project 'DroneWatchDJIBootstrap.xcodeproj'

  # Direct iOS DJI Mobile SDK path for Issue #2.
  pod 'DJI-SDK-iOS', '~> 4.16.2'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
